server:
  port: 8080


mybatis:
  one:
    url: jdbc:mysql://localhost:3306/one?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.mysql.cj.jdbc.Driver
  two:
    url: jdbc:mysql://localhost:3306/two?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.mysql.cj.jdbc.Driver

